on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.addLabels({
            issue_number: context.issue.number,
            labels: ['triage']
            })
